import { WorkoutDay } from "./types";

export const MUST_TRACK_BASELINES: Record<string, string> = {
  pull_ups: "Max about 14 reps",
  dips: "Max about 12 reps",
  handstand_pushups: "Wall HSPU about 3-4 reps",
  farmer_carry: "20 kg for 100 meters",
  back_extensions: "12 reps",
  dead_hang: "1 minute 16 seconds",
  weighted_squat: "65-85 kg possible",
  bulgarian_split_squat: "Track reps and control",
  nordic_hamstring_curl: "Track clean reps",
  single_leg_romanian_deadlift: "Track reps and balance",
  hip_thrust: "Track reps and load",
  tibialis_raise: "Track clean reps",
  single_leg_calf_raise: "Track clean reps",
  sprint_time: "6 rounds of 10-15 seconds",
  broad_jump_distance: "Improve slowly",
};

export const DEFAULT_WORKOUTS: WorkoutDay[] = [
  {
    id: "monday-upper-strength",
    day: "Monday",
    name: "Upper Strength + Muscle + Grip",
    sections: [
      {
        name: "Warm-up",
        exercises: [
          {
            id: "shoulder-cars",
            name: "Shoulder CARs",
            type: "time",
            sets: 1,
            secondsMin: 90,
            secondsMax: 120,
            isBareMinimum: true,
            notes: "Smooth circles both directions.",
          },
          {
            id: "scap-push-ups",
            name: "Scap push-ups",
            type: "reps",
            sets: 1,
            repsMin: 8,
            repsMax: 12,
          },
        ],
      },
      {
        name: "Main Work",
        exercises: [
          {
            id: "pull-ups",
            progressKey: "pull_ups",
            name: "Pull-ups",
            type: "reps",
            sets: 3,
            repsMin: 6,
            repsMax: 8,
            restSeconds: 90,
            isBareMinimum: true,
            isMustTrack: true,
          },
          {
            id: "dips",
            progressKey: "dips",
            name: "Dips",
            type: "reps",
            sets: 3,
            repsMin: 6,
            repsMax: 8,
            restSeconds: 90,
            isBareMinimum: true,
            isMustTrack: true,
          },
          {
            id: "push-ups",
            name: "Push-ups",
            type: "reps",
            sets: 2,
            repsMin: 20,
            repsMax: 30,
            restSeconds: 75,
          },
          {
            id: "farmer-carry",
            progressKey: "farmer_carry",
            name: "Farmer carry",
            type: "carry",
            sets: 3,
            weightKg: 20,
            distance: 40,
            distanceUnit: "m",
            restSeconds: 90,
            isBareMinimum: true,
            isMustTrack: true,
          },
          {
            id: "dead-hang",
            progressKey: "dead_hang",
            name: "Dead hang",
            type: "time",
            sets: 2,
            secondsMin: 30,
            secondsMax: 45,
            restSeconds: 60,
            isBareMinimum: true,
            isMustTrack: true,
          },
        ],
      },
      {
        name: "Mobility",
        exercises: [
          {
            id: "wrist-mobility",
            name: "Wrist mobility",
            type: "time",
            sets: 1,
            secondsMin: 90,
            secondsMax: 120,
            isBareMinimum: true,
          },
        ],
      },
    ],
  },
  {
    id: "tuesday-lower-strength",
    day: "Tuesday",
    name: "Lower Strength + Tendons",
    sections: [
      {
        name: "Warm-up",
        exercises: [
          {
            id: "hip-ankle-warmup",
            name: "Hip + ankle warm-up",
            type: "time",
            sets: 1,
            secondsMin: 180,
            secondsMax: 240,
            isBareMinimum: true,
          },
        ],
      },
      {
        name: "Main Work",
        exercises: [
          {
            id: "weighted-squat",
            progressKey: "weighted_squat",
            name: "Weighted squat",
            type: "weight_reps",
            sets: 4,
            repsMin: 5,
            repsMax: 6,
            weightKg: 70,
            restSeconds: 120,
            isBareMinimum: true,
            isMustTrack: true,
            notes: "Use the available safe load.",
          },
          {
            id: "bulgarian-split-squat",
            progressKey: "bulgarian_split_squat",
            name: "Bulgarian split squat",
            type: "weight_reps",
            sets: 3,
            repsMin: 6,
            repsMax: 8,
            weightKg: 0,
            restSeconds: 90,
            isMustTrack: true,
          },
          {
            id: "nordic-hamstring-curl",
            progressKey: "nordic_hamstring_curl",
            name: "Nordic hamstring curl",
            type: "reps",
            sets: 3,
            repsMin: 3,
            repsMax: 5,
            restSeconds: 90,
            isBareMinimum: true,
            isMustTrack: true,
          },
          {
            id: "single-leg-romanian-deadlift",
            progressKey: "single_leg_romanian_deadlift",
            name: "Single-leg Romanian deadlift",
            type: "weight_reps",
            sets: 3,
            repsMin: 6,
            repsMax: 8,
            weightKg: 12,
            restSeconds: 90,
            isMustTrack: true,
          },
          {
            id: "tibialis-raise",
            progressKey: "tibialis_raise",
            name: "Tibialis raise",
            type: "reps",
            sets: 2,
            repsMin: 15,
            repsMax: 20,
            restSeconds: 45,
            isBareMinimum: true,
            isMustTrack: true,
          },
          {
            id: "single-leg-calf-raise",
            progressKey: "single_leg_calf_raise",
            name: "Single-leg calf raise",
            type: "reps",
            sets: 2,
            repsMin: 10,
            repsMax: 15,
            restSeconds: 45,
            isMustTrack: true,
          },
        ],
      },
      {
        name: "Mobility",
        exercises: [
          {
            id: "couch-stretch",
            name: "Couch stretch",
            type: "time",
            sets: 1,
            secondsMin: 120,
            secondsMax: 180,
            isBareMinimum: true,
          },
        ],
      },
    ],
  },
  {
    id: "wednesday-zone2-neck",
    day: "Wednesday",
    name: "Zone 2 + Light Neck/Mobility",
    sections: [
      {
        name: "Conditioning",
        exercises: [
          {
            id: "zone-2-cardio",
            name: "Zone 2 cardio",
            type: "time",
            sets: 1,
            secondsMin: 1200,
            secondsMax: 1800,
            isBareMinimum: true,
          },
        ],
      },
      {
        name: "Mobility",
        exercises: [
          {
            id: "neck-isometrics",
            name: "Light neck isometrics",
            type: "time",
            sets: 1,
            secondsMin: 90,
            secondsMax: 120,
            isBareMinimum: true,
          },
          {
            id: "thoracic-opener",
            name: "Thoracic opener",
            type: "time",
            sets: 1,
            secondsMin: 120,
            secondsMax: 180,
          },
          {
            id: "dead-hang",
            progressKey: "dead_hang",
            name: "Dead hang",
            type: "time",
            sets: 1,
            secondsMin: 30,
            secondsMax: 45,
            restSeconds: 0,
            isBareMinimum: true,
            isMustTrack: true,
          },
        ],
      },
    ],
  },
  {
    id: "thursday-upper-power",
    day: "Thursday",
    name: "Upper Power + Rotation + Punching Bag",
    sections: [
      {
        name: "Warm-up",
        exercises: [
          {
            id: "shadow-boxing-warmup",
            name: "Shadow boxing warm-up",
            type: "time",
            sets: 1,
            secondsMin: 180,
            secondsMax: 300,
            isBareMinimum: true,
          },
        ],
      },
      {
        name: "Main Work",
        exercises: [
          {
            id: "handstand-push-ups",
            progressKey: "handstand_pushups",
            name: "Handstand push-ups",
            type: "reps",
            sets: 4,
            repsMin: 3,
            repsMax: 4,
            restSeconds: 90,
            isBareMinimum: true,
            isMustTrack: true,
          },
          {
            id: "pull-ups",
            progressKey: "pull_ups",
            name: "Pull-ups",
            type: "reps",
            sets: 3,
            repsMin: 4,
            repsMax: 6,
            restSeconds: 90,
            isMustTrack: true,
          },
          {
            id: "dips",
            progressKey: "dips",
            name: "Dips",
            type: "reps",
            sets: 3,
            repsMin: 5,
            repsMax: 6,
            restSeconds: 90,
            isBareMinimum: true,
            isMustTrack: true,
          },
          {
            id: "push-ups-power",
            name: "Push-ups",
            type: "reps",
            sets: 2,
            repsMin: 20,
            repsMax: 30,
            restSeconds: 60,
          },
        ],
      },
      {
        name: "Main Work",
        exercises: [
          {
            id: "rotational-throws",
            name: "Rotational throws",
            type: "reps",
            sets: 3,
            repsMin: 6,
            repsMax: 8,
            restSeconds: 60,
          },
        ],
      },
      {
        name: "Conditioning",
        exercises: [
          {
            id: "punching-bag-rounds",
            name: "Punching bag rounds",
            type: "time",
            sets: 4,
            secondsMin: 90,
            secondsMax: 120,
            restSeconds: 60,
            isBareMinimum: true,
          },
        ],
      },
    ],
  },
  {
    id: "friday-prehab-coordination",
    day: "Friday",
    name: "Joint Health + Mobility + Balance + Prehab + Coordination",
    sections: [
      {
        name: "Warm-up",
        exercises: [
          {
            id: "joint-circles",
            name: "Joint circles",
            type: "time",
            sets: 1,
            secondsMin: 180,
            secondsMax: 240,
            isBareMinimum: true,
          },
        ],
      },
      {
        name: "Main Work",
        exercises: [
          {
            id: "back-extensions",
            progressKey: "back_extensions",
            name: "Back extensions",
            type: "reps",
            sets: 3,
            repsMin: 10,
            repsMax: 12,
            restSeconds: 60,
            isBareMinimum: true,
            isMustTrack: true,
          },
          {
            id: "nordic-hamstring-curl",
            progressKey: "nordic_hamstring_curl",
            name: "Nordic hamstring curl",
            type: "reps",
            sets: 2,
            repsMin: 3,
            repsMax: 4,
            restSeconds: 90,
            isMustTrack: true,
          },
          {
            id: "tibialis-raise",
            progressKey: "tibialis_raise",
            name: "Tibialis raise",
            type: "reps",
            sets: 2,
            repsMin: 15,
            repsMax: 20,
            restSeconds: 45,
            isBareMinimum: true,
            isMustTrack: true,
          },
          {
            id: "single-leg-calf-raise",
            progressKey: "single_leg_calf_raise",
            name: "Single-leg calf raise",
            type: "reps",
            sets: 2,
            repsMin: 10,
            repsMax: 15,
            restSeconds: 45,
            isMustTrack: true,
          },
          {
            id: "single-leg-romanian-deadlift",
            progressKey: "single_leg_romanian_deadlift",
            name: "Single-leg Romanian deadlift",
            type: "weight_reps",
            sets: 2,
            repsMin: 6,
            repsMax: 8,
            weightKg: 8,
            restSeconds: 60,
            isBareMinimum: true,
            isMustTrack: true,
          },
        ],
      },
      {
        name: "Mobility",
        exercises: [
          {
            id: "balance-flow",
            name: "Balance flow",
            type: "time",
            sets: 1,
            secondsMin: 180,
            secondsMax: 300,
            isBareMinimum: true,
          },
          {
            id: "deep-squat-breathing",
            name: "Deep squat breathing",
            type: "time",
            sets: 1,
            secondsMin: 120,
            secondsMax: 180,
          },
        ],
      },
    ],
  },
  {
    id: "saturday-lower-power",
    day: "Saturday",
    name: "Lower Power + Agility + Core + Carries / Sprints",
    sections: [
      {
        name: "Warm-up",
        exercises: [
          {
            id: "dynamic-leg-warmup",
            name: "Dynamic leg warm-up",
            type: "time",
            sets: 1,
            secondsMin: 180,
            secondsMax: 300,
            isBareMinimum: true,
          },
        ],
      },
      {
        name: "Main Work",
        exercises: [
          {
            id: "broad-jump-distance",
            progressKey: "broad_jump_distance",
            name: "Broad jump distance",
            type: "jump",
            sets: 5,
            distance: 180,
            distanceUnit: "cm",
            restSeconds: 60,
            isBareMinimum: true,
            isMustTrack: true,
          },
          {
            id: "sprint-time",
            progressKey: "sprint_time",
            name: "Sprint time",
            type: "sprint",
            sets: 6,
            secondsMin: 10,
            secondsMax: 15,
            restSeconds: 90,
            isBareMinimum: true,
            isMustTrack: true,
          },
          {
            id: "hip-thrust",
            progressKey: "hip_thrust",
            name: "Hip thrust",
            type: "weight_reps",
            sets: 3,
            repsMin: 8,
            repsMax: 10,
            weightKg: 70,
            restSeconds: 120,
            isMustTrack: true,
          },
        ],
      },
      {
        name: "Core",
        exercises: [
          {
            id: "side-plank",
            name: "Side plank",
            type: "time",
            sets: 2,
            secondsMin: 30,
            secondsMax: 45,
            restSeconds: 30,
            isBareMinimum: true,
          },
          {
            id: "hollow-hold",
            name: "Hollow hold",
            type: "time",
            sets: 2,
            secondsMin: 25,
            secondsMax: 40,
            restSeconds: 30,
          },
        ],
      },
      {
        name: "Carries",
        exercises: [
          {
            id: "farmer-carry",
            progressKey: "farmer_carry",
            name: "Farmer carry",
            type: "carry",
            sets: 3,
            weightKg: 20,
            distance: 50,
            distanceUnit: "m",
            restSeconds: 90,
            isBareMinimum: true,
            isMustTrack: true,
          },
        ],
      },
    ],
  },
];
